---
vms:

  # NOTE: All `box:` declarations in this example point to vagrantcloud.com
  # and require Vagrant 1.5.0 or newer to function.

  - name: master-vagrant.cloud.puppetlabs.net
    box: puppetlabs/debian-7.5-64-puppet
    provision: :hosts
    roles:
      - 2gb-memory
      - base
      - master
